# Generated by Django 4.2.3 on 2023-07-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('descrizione', models.CharField(max_length=250)),
                ('contenuto', models.TextField()),
                ('data_inizio', models.DateField()),
                ('durata_ore', models.DecimalField(decimal_places=3, max_digits=3)),
                ('prezzo', models.DecimalField(decimal_places=10, max_digits=10)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
