# Generated by Django 4.2.3 on 2023-07-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCorsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('descrizione', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Corsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('img', models.ImageField(default=None, upload_to='img/corsi')),
                ('descrizione', models.TextField()),
                ('durata_ore', models.CharField(max_length=4)),
                ('data_inizio', models.DateTimeField()),
                ('prezzo', models.FloatField(max_length=6)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoriacorsi')),
            ],
            options={
                'verbose_name_plural': 'Corsi',
            },
        ),
        migrations.CreateModel(
            name='Alunni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.corsi')),
            ],
            options={
                'verbose_name_plural': 'Alunni',
            },
        ),
    ]
