# Generated by Django 4.2.3 on 2023-07-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCorsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Corsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('durata_ore', models.CharField(max_length=4)),
                ('data_inizio', models.DateTimeField()),
                ('prezzo', models.FloatField(max_length=6)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoriacorsi')),
            ],
        ),
    ]
