# Generated by Django 4.2.3 on 2023-07-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacorsi',
            options={'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='corsi',
            options={'verbose_name_plural': 'Corsi'},
        ),
        migrations.CreateModel(
            name='Alunni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.corsi')),
            ],
            options={
                'verbose_name_plural': 'Alunni',
            },
        ),
    ]
