# Generated by Django 4.2.3 on 2023-07-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunni',
            name='img_prof',
            field=models.ImageField(default=None, upload_to='img/alunni', verbose_name='Inserisci Immagine di profilo'),
            preserve_default=False,
        ),
    ]
