# Generated by Django 4.2.3 on 2023-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='titolo',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
